name: Guardian Scraper (hourly)

on:
  push:                     # Executa ao fazer push
  schedule:
    - cron: '0 * * * *'  # Executa de hora a hora
  workflow_dispatch:      # Permite executar manualmente no GitHub

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      contents: write       # Permite fazer commits no repositório

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        pip install requests

    - name: Executar o script de scraping
      env:
        GUARDIAN_API_KEY: ${{ secrets.GUARDIAN_API_KEY }}
      run: |
        python guardian_scraper.py

    - name: Fazer commit e push dos novos artigos e logs
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add artigos/*.json logs/*.log
        git commit -m "Atualização automática de artigos e logs [${{ github.run_id }}]" || echo "Nada para commitar"
        git push
